-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, CAR_ID, count(HISTORY_ID) as RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
where CAR_ID IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') between "2022-08-01" and "2022-10-31"
    group by CAR_ID
    HAVING count(CAR_ID) >= 5
    ) AND (DATE_FORMAT(START_DATE, '%Y-%m-%d') between "2022-08-01" and "2022-10-31")
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC