-- 코드를 입력하세요
# SELECT * FROM REST_INFO 
# SELECT * FROM REST_REVIEW
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, round(avg(B.REVIEW_SCORE),2) as SCORE FROM REST_INFO A
JOIN REST_REVIEW B
ON A.REST_ID=B.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS like '서울%'
ORDER BY avg(B.REVIEW_SCORE) DESC,  A.FAVORITES DESC